// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrin7M2uMktSbB9W8AGzo3sYg23_ZIGIg',
    appId: '1:674193039753:web:25f9401ee10cc98a7d0158',
    messagingSenderId: '674193039753',
    projectId: 'flutter-emergency-phone',
    authDomain: 'flutter-emergency-phone.firebaseapp.com',
    storageBucket: 'flutter-emergency-phone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1tXmE5FL__TvhfkHB0R_YyVX2sf204qo',
    appId: '1:674193039753:android:e04acec6ca061e307d0158',
    messagingSenderId: '674193039753',
    projectId: 'flutter-emergency-phone',
    storageBucket: 'flutter-emergency-phone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdZUNEu-brOLujFcYV9s4cZF5ED29VfrM',
    appId: '1:674193039753:ios:d3ce1857d2acc88f7d0158',
    messagingSenderId: '674193039753',
    projectId: 'flutter-emergency-phone',
    storageBucket: 'flutter-emergency-phone.appspot.com',
    iosClientId: '674193039753-7g0k3aaab44d53jseivt14so548et16s.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyPhone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdZUNEu-brOLujFcYV9s4cZF5ED29VfrM',
    appId: '1:674193039753:ios:d3ce1857d2acc88f7d0158',
    messagingSenderId: '674193039753',
    projectId: 'flutter-emergency-phone',
    storageBucket: 'flutter-emergency-phone.appspot.com',
    iosClientId: '674193039753-7g0k3aaab44d53jseivt14so548et16s.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyPhone',
  );
}
